[package]
name = "culebra"
version = "0.1.0"
authors = ["Ernesto Men√©ndez <pyalec@gmail.com>"]

[[bin]]
name = "culebra-client"
path = "src/client.rs"

[[bin]]
name = "culebra-server"
path = "src/server.rs"

[dependencies]
piston = "0.25.0"
piston_window = "0.52.0"
rustc-serialize = "0.3.19"
